# Generated by Django 4.2.16 on 2024-11-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='movie_style',
        ),
    ]
